### PR TITLE
post on MG wide coverage parser

### PR DESCRIPTION
**Pull request by aniellodesanto**

### CODE REVIEW

**Comment by thomas--graf** [comment]
Nice read. Minor nitpicks:

1. Is the complexity correct? I'm a bit thrown off by the 8 in there.
1. Can you insert a summary start marker before the first paragraph and an end marker after the second paragraph?
1. Undo the changes in `references.bib` (extra empty lines)

**Comment by thomas--graf** [comment]
Oh, and change the date to tomorrow, I won't push this out today.

**Comment by aniellodesanto** [comment]
> 1. Is the complexity correct? I'm a bit thrown off by the 8 in there.

Damn. Of course it's not, missing {}.

> 2. Can you insert a summary start marker before the first paragraph and an end marker after the second paragraph?

Uhm you mean like a ---? Or is there a dedicated "summary marker" I'm unaware of?
 
> 3. Undo the changes in `references.bib` (extra empty lines)

Damn^2. Will do.

**Comment by aniellodesanto** [comment]
> Uhm you mean like a ---? Or is there a dedicated "summary marker" I'm unaware of?
> 
Nevermind. Got it.

**Pull request merged**
